#!/bin/php
<?php
/**
 * Copyright (c) 2011 Pat Fox
 * Dual licensed under the MIT (http://www.opensource.org/licenses/mit-license.php) and GPL (http://www.gnu.org/licenses/gpl.html) licenses
 * http://code.google.com/p/ssearch
 */

/**
 * Command-line interface handler script for sSearch
 *
 * IT IS STRONGLY RECOMMENDED THAT YOU DO NOT EDIT THIS FILE
 * IF YOU NEED TO CHANGE THIS FILE, YOU SHOULD CREATE A COPY AND EDIT THAT
 */

$pathinfo = pathinfo( __FILE__ );
require_once( $pathinfo[ 'dirname' ] . '/core/sSearchCLIHandler.class.php' );
$handler = new sSearchCLIHandler($argv);
?>
